FROM meltano/meltano

# Install git
RUN apt-get update && apt-get install -y git

# Copy the initialization script into the container
COPY init-script.sh /init-script.sh

# Make the script executable
RUN chmod +x /init-script.sh

# Set the script as the entry point
ENTRYPOINT ["/init-script.sh"]
